### PR TITLE
fix: browser names should respect selenium's definition

### PR DESCRIPTION
**Pull request by link89**

### CODE REVIEW

**Comment by link89** [comment]
Hi @alexschwantes Can you kindly approve this PR as it breaks our automation job.

**Comment by alexschwantes** [comment]
Hi @link89,
This was an intentional, breaking change, which is why the major version number was increased to v1.0.0. It was also listed in the [release notes](https://github.com/alexschwantes/testcafe-browser-provider-selenium/releases/tag/v1.0.0) for this version. 

Testcafe uses the browser names/Alias' `ie` and `edge`. So this change was done to bring the plugin in line with how Testcafe references browser names. 

This is also how other similar browser provider plugins such as https://github.com/DevExpress/testcafe-browser-provider-browserstack work. So the recommended fix would be to just update your automation jobs to use the new alias'. 

Sorry for the inconvenience.

**Comment by link89** [comment]
> Testcafe uses the browser names/Alias' ie and edge. So this change was done to bring the plugin in line with how Testcafe references browser names.

This patch doesn't change this fact. It is OK for me to use `selenium:edge`. 
The problem is you need to translate this name to its selenium name `MicrosoftEdge` inside the provider or else selenium won't able to start Edge browser for you.

**Comment by alexschwantes** [comment]
@link89 ah, yes I see now, sorry for the misunderstanding.

**Comment by alexschwantes** [comment]
v1.0.1 has now been released with this patch

**Pull request merged**
